/* generated by lucb */
#include "lucb_rt.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdatomic.h>
#include <pthread.h>
#include <sched.h>
#include <time.h>
#include <unistd.h>
typedef struct lb_Handle { size_t id; } lb_Handle;

typedef struct lb_W lb_W;
LB_RES(size_t, lb_r_usize);
typedef struct lb_W {
    lb_span data;
    size_t used;
} lb_W;

typedef struct lb_a_u8_64_ { uint8_t d[64]; } lb_a_u8_64_;
LB_OPT(int64_t, lb_o_i64);
LB_RES(uint32_t, lb_r_u32);
LB_RES(int64_t, lb_r_i64);
LB_RES(int32_t, lb_r_i32);
typedef uint32_t (*lb_fn_u32_to_ErrorCode)(uint32_t);

lb_r_unit lb_f(lb_str lb_what);
lb_r_unit lb_g(lb_o_i64 lb_x);
lb_r_u32 lb_fv(lb_str lb_what);
lb_r_i64 lb_h(lb_o_i64 lb_x);
lb_r_i64 lb_h2(lb_o_i64 lb_x);
lb_r_unit lb_fail_never(lb_str lb_what);
lb_r_usize lb_W_write(lb_W* self, lb_cspan lb_bytes);
lb_r_unit lb_k(lb_iface lb_w);
lb_r_i32 lb_main(lb_span lb_arguments);
uint32_t lb_bad = (uint32_t)(1ULL);
typedef struct lb_vt_Writer {
    lb_r_usize (*write)(void* self, lb_cspan);
} lb_vt_Writer;
static lb_r_usize lb_file_write(void* self, lb_cspan bytes) {
    FILE* f = (FILE*)self;
    size_t n = bytes.length == 0 ? 0 : fwrite(bytes.data, 1, bytes.length, f);
    fflush(f);
    lb_r_usize r; r.failed = false; r.value = n; return r;
}
static const lb_vt_Writer lb_vt_file __attribute__((unused)) = { .write = lb_file_write };

static const lb_vt_Writer lb_vt_W_Writer __attribute__((unused)) = {
    .write = (lb_r_usize (*)(void*, lb_cspan))lb_W_write,
};


lb_r_usize lb_W_write(lb_W* self, lb_cspan lb_bytes) {
    size_t lb_i __attribute__((unused)) = 0ULL;
    while (!!((((size_t)(lb_i)) < ((size_t)((lb_bytes.length)))))) {
        {
            (((uint8_t*)self->data.data)[(lb_check_index((uint64_t)(self->used), self->data.length), self->used)]) = (((uint8_t*)lb_bytes.data)[(lb_check_index((uint64_t)(lb_i), lb_bytes.length), lb_i)]);
            self->used = (size_t)(lb_add_u((uint64_t)(self->used), (uint64_t)(1ULL), 64));
            lb_i = (size_t)(lb_add_u((uint64_t)(lb_i), (uint64_t)(1ULL), 64));
        }
    }
    return ((lb_r_usize){ .value = ((lb_bytes.length)), .failed = false });
    lb_trap("unreachable");
}

lb_r_unit lb_f(lb_str lb_what) {
    return ((lb_r_unit){ .error = { .code = (int32_t)(lb_bad), .message = lb_what }, .failed = true });
    return ((lb_r_unit){ .failed = false });
}

lb_r_unit lb_g(lb_o_i64 lb_x) {
    int64_t lb_v __attribute__((unused)) = ({ lb_o_i64 _lb_o0 = lb_x; if (!_lb_o0.present) { return ((lb_r_unit){ .failed = false }); } _lb_o0.value; });
    (void)(((void)(lb_v)));
    return ((lb_r_unit){ .failed = false });
}

lb_r_u32 lb_fv(lb_str lb_what) {
    return ((lb_r_u32){ .error = { .code = (int32_t)(lb_bad), .message = lb_what }, .failed = true });
    lb_trap("unreachable");
}

lb_r_i64 lb_h(lb_o_i64 lb_x) {
    int64_t lb_v __attribute__((unused)) = ({ lb_o_i64 _lb_o2 = lb_x; if (!_lb_o2.present) { return ((lb_r_i64){ .value = ((int64_t)(lb_conv_u((uint64_t)((({ lb_r_u32 _lb_r3 = lb_fv(((lb_str){"no", 2})); if (_lb_r3.failed) { return ((lb_r_i64){ .error = _lb_r3.error, .failed = true }); } _lb_r3.value; }))), 32, 0, 64, 1, 1))), .failed = false }); } _lb_o2.value; });
    return ((lb_r_i64){ .value = (lb_v), .failed = false });
    lb_trap("unreachable");
}

lb_r_i64 lb_h2(lb_o_i64 lb_x) {
    int64_t lb_v __attribute__((unused)) = ({ lb_o_i64 _lb_o4 = lb_x; if (!_lb_o4.present) { (void)(({ lb_r_unit _lb_r5 = lb_fail_never(((lb_str){"no", 2})); if (_lb_r5.failed) { return ((lb_r_i64){ .error = _lb_r5.error, .failed = true }); } (void)0; })); __builtin_unreachable(); } _lb_o4.value; });
    return ((lb_r_i64){ .value = (lb_v), .failed = false });
    lb_trap("unreachable");
}

lb_r_unit lb_fail_never(lb_str lb_what) {
    return ((lb_r_unit){ .error = { .code = (int32_t)(lb_bad), .message = lb_what }, .failed = true });
    lb_trap("unreachable");
}

lb_r_unit lb_k(lb_iface lb_w) {
    (void)(({ lb_r_usize _lb_r6 = ({ lb_iface _lb_if7 = lb_w; ((lb_vt_Writer*)_lb_if7.vtable)->write(_lb_if7.data, ({ lb_str _lb_sp8 = ((lb_str){"abc", 3}); (lb_cspan){ (void*)(_lb_sp8.data), _lb_sp8.length }; })); }); if (_lb_r6.failed) { return ((lb_r_unit){ .error = _lb_r6.error, .failed = true }); } _lb_r6.value; }));
    return ((lb_r_unit){ .failed = false });
}

lb_r_i32 lb_main(lb_span lb_arguments) {
    lb_a_u8_64_ lb_buf __attribute__((unused)) = {0};
    lb_W lb_w __attribute__((unused)) = (lb_W){.data = ((lb_span){lb_buf.d, 64ULL}), .used = 0ULL};
    (void)(({ lb_r_unit _lb_r9 = lb_k(((lb_iface){ (void*)(&lb_w), &lb_vt_W_Writer })); if (_lb_r9.failed) { return ((lb_r_i32){ .error = _lb_r9.error, .failed = true }); } (void)0; }));
    (void)(({ lb_r_unit _lb_r10 = lb_g(((lb_o_i64){ .present = false })); int _lb_v10 = {0}; if (_lb_r10.failed) { lb_error lb_e __attribute__((unused)) = _lb_r10.error; {
    (void)(({ fwrite(lb_e.message.data, 1, lb_e.message.length, stdout); fputs(" ", stdout); fwrite(({ lb_span _lb_sc11 = ((void)lb_check_index((uint64_t)(0), (uint64_t)(64ULL) + 1), (void)lb_check_index((uint64_t)(lb_w.used), (uint64_t)(64ULL) + 1), (lb_span){(void*)((lb_buf.d) + (0)), (size_t)((lb_w.used) - (0))}); const char* _lb_sb11 = (const char*)_lb_sc11.data; size_t _lb_sl11 = _lb_sc11.length; (lb_str){ _lb_sb11, _lb_sl11 }; }).data, 1, ({ lb_span _lb_sc11 = ((void)lb_check_index((uint64_t)(0), (uint64_t)(64ULL) + 1), (void)lb_check_index((uint64_t)(lb_w.used), (uint64_t)(64ULL) + 1), (lb_span){(void*)((lb_buf.d) + (0)), (size_t)((lb_w.used) - (0))}); const char* _lb_sb11 = (const char*)_lb_sc11.data; size_t _lb_sl11 = _lb_sc11.length; (lb_str){ _lb_sb11, _lb_sl11 }; }).length, stdout); fputc('\n', stdout); (void)0; }));
    (void)(((void)0));
    goto _lb_cd10;
}
__attribute__((unused)) _lb_cd10: ; } else { } _lb_v10; }));
    int64_t _lb_m12 = 3LL;
    switch ((int64_t)(_lb_m12)) {
        case 1LL:
        {
            {
                (void)(lb_print_str(((lb_str){"one", 3})));
            }
            break;
        }
        default:
        {
            {
                (void)(((void)(0LL)));
            }
            break;
        }
    }
    return ((lb_r_i32){ .value = (0LL), .failed = false });
    lb_trap("unreachable");
}

int main(int argc, char** argv) {
    lb_set_alloc(lb_heap_alloc());
    lb_span args = { (void*)argv, (size_t)argc };
    lb_r_i32 r = lb_main(args);
    if (r.failed) { fprintf(stderr, "error %d: %.*s\n", r.error.code, (int)r.error.message.length, r.error.message.data); return 1; }
    return (int)r.value;
}
